### ISSUE TITLE
result doesn't match expected

### ISSUE THREAD

**Issue by digininja** [texttheater/golang-levenshtein#11]
I'm comparing a few different Levenshtein libraries and yours comes up with different values for my test cases:

- The distance between 'Orange' and 'Apple' computed as 9. - Expected 5
- The distance between 'kitten' and 'sitting' computed as 5. - Expected 3

I've checked with a few online checkers as well and they match my expected values. Is there a bug or are you calculating something different to the others?

The code I'm using is taken from your examples:

```go
package main

import "fmt"
import "github.com/texttheater/golang-levenshtein/levenshtein"

func main() {
    source := "kitten"
    target := "sitting"
    distance := levenshtein.DistanceForStrings([]rune(source), []rune(target), levenshtein.DefaultOptions)
    fmt.Printf("The distance between '%s' and '%s' computed as %d.\n", source, target, distance)
}
```

**Comment by digininja** [comment]
Can't complain at that customer service :)

**Comment by texttheater** [comment]
Thanks for the report! :)
