### ISSUE TITLE
DistanceForStrings: Initialization costs don't match options

### ISSUE THREAD

**Issue by mehdiym** [texttheater/golang-levenshtein#12]
Hello and thank you for your lib.
In your DistanceForStrings method, initialization costs should match insert/delete costs on lines 91, 94 and 102.
Currently it supposes costs are 1, but if you increase option costs you get wrong results.

Let's suppose insert and delete costs are 2, then if you compute distance between "meme" and "me", you'll get 2 instead of 4.

In the mentioned lines, I multiplied the value by the corresponding costs and now it works fine.

**Comment by texttheater** [comment]
Oops - thanks for the detailed bug report! Fixed now.
